### ISSUE TITLE
Upgrade use of https://addons.mozilla.org/api/v3/ to /api/v4/ 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/taar_gcp_etl#14]
AMO api v3 is [deprecated](https://blog.mozilla.org/addons/2021/02/01/addons-mozilla-org-api-v3-deprecation/) - and was scheduled to be removed entirely at the end of 2021.  We're hoping to [finally remove](https://github.com/mozilla/addons-server/issues/18759#issuecomment-1033300945) it very soon.  From a search on https://github.com/mozilla/ we've noted some use in this repo of the /api/v3 endpoint that will break once the api is deleted.  

In many cases just replacing `/api/v3/` with `/api/v4/` is sufficient but some fields/endpoints have been renamed/removed (there's a lengthy v4 [changelog](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#v4-api-changelog)).

If on the other hand those files/this repo is no longer in use/maintained please close the issue so we can mark it off our list,
thanks.

**Comment by eu9ene** [comment]
I compared results for APIs we use:

https://addons.mozilla.org/api/v4/addons/addon/firefox@ghostery.com/versions/
New field added - is_custom

https://addons.mozilla.org/api/v4/discovery/editorial/?recommended=true
No changes

https://addons.mozilla.org/api/v3/addons/search/?app=firefox&sort=created&type=extension
New field added - is_custom
**Removed**
is_source_public - no usage
**is_featured - usage in taar_gcp_etl**

Where `is_features` is used:
https://github.com/mozilla/taar_gcp_etl/blob/d22ece45302bda4ef752e3fe0a9d3c99252ef25d/taar_etl/taar_amowhitelist.py#L52
https://github.com/mozilla/taar_gcp_etl/blob/d22ece45302bda4ef752e3fe0a9d3c99252ef25d/taar_etl/taar_amowhitelist.py#L105
It seems it is used to whitelist the addons.

Removing `is_featured` is a breaking change. @eviljeff do you have any insights into why it was removed and what's the replacement?

**Comment by diox** [comment]
`is_featured` was replaced by `promoted`, which is more expressive. It can be `null`, or an object containing the `category` of promotion and the `apps` the promotion is relevant for. Assuming you don't care about the apps, the equivalent to `is_featured` is `promoted.category` set to `recommended`.
